# crowdin.yml (リポジトリのrootに配置)

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "docs"

files:
  - source: "_build/gettext/**/*.pot"
    translation: "locales/%language%/LC_MESSAGES/%original_path%/%file_name%.po"